substitutions:
    name: base-board
    friendly_name: Base Board

esphome:
    name: ${name}
    friendly_name: ${friendly_name}

logger:
    level: INFO

api:

ota:
    - platform: esphome

wifi:
    ssid: !secret wifi_ssid
    password: !secret wifi_password

    ap:
        ssid: Huya-WiFi

mdns:
    disabled: false

captive_portal:

button:
    - platform: restart
      name: MCU Restart
      id: mcu_restart

sensor:
    - platform: uptime
      name: Uptime
      id: mcu_uptime
      unit_of_measurement: s
      device_class: duration
      state_class: measurement

    - platform: wifi_signal
      name: WiFi Signal
      id: mcu_wifi_signal

    - platform: internal_temperature
      name: MCU Temperature
      id: mcu_temperature

binary_sensor:
    - platform: status
      name: Status
      id: mcu_status

text_sensor:
    # Human-friendly uptime string
    - platform: template
      name: Uptime (pretty)
      id: mcu_uptime_pretty
      update_interval: 60s
      icon: mdi:clock-outline
      entity_category: diagnostic
      lambda: |-
        const uint32_t secs = (uint32_t) id(mcu_uptime).state;
        uint32_t days  = secs / 86400;
        uint32_t hours = (secs % 86400) / 3600;
        uint32_t mins  = (secs % 3600) / 60;
        uint32_t s     = secs % 60;
        char buf[48];
        if (days > 0)       snprintf(buf, sizeof(buf), "%ud %uh %um", days, hours, mins);
        else if (hours > 0) snprintf(buf, sizeof(buf), "%uh %um %us", hours, mins, s);
        else if (mins > 0)  snprintf(buf, sizeof(buf), "%um %us", mins, s);
        else                snprintf(buf, sizeof(buf), "%us", s);
        return std::string(buf);
    - platform: wifi_info
      ip_address:
          name: IP
          id: mcu_ip
      ssid:
          name: SSID
          id: mcu_ssid
      bssid:
          name: BSSID
          id: mcu_bssid
      mac_address:
          name: MAC Address
          id: mcu_mac_address

    - platform: version
      name: ESPhome Version
      id: mcu_version_esphome
      hide_timestamp: true

time:
    - platform: homeassistant
      id: ha_time