substitutions:
    name: base-board-nodemcu-32s
    friendly_name: Base Board NodeMCU-32S

packages:
    Base Board Template (ESPHome): github://ngorchilov/huya-configs/base-board-template-esphome.yaml

esp32:
    board: nodemcu-32s