substitutions:
    name: base-board
    friendly_name: Base Board

esphome:
    name: ${name}
    friendly_name: ${friendly_name}

logger:

api:

ota:
    - platform: esphome

wifi:
    ssid: !secret wifi_ssid
    password: !secret wifi_password

    ap:
        ssid: Huya-WiFi

captive_portal:

button:
    - platform: restart
      name: Restart

sensor:
    - platform: uptime
      name: Uptime

    - platform: wifi_signal
      name: WiFi Signal

    - platform: internal_temperature
      name: Internal Temperature

binary_sensor:
    - platform: status
      name: Status

text_sensor:
    - platform: wifi_info
      ip_address:
          name: IP
      ssid:
          name: SSID
      bssid:
          name: BSSID
      mac_address:
          name: MAC Address
          id: mac_address

    - platform: version
      name: Version
#     hide_timestamp: true

time:
    - platform: homeassistant
      id: ha_time
