substitutions:
  name: base-board-cb2s
  friendly_name: Base Board CB2S

packages:
  Base Board Template (BEKEN): github://ngorchilov/huya-configs/base-board-template-libretiny-beken.yaml

bk72xx:
  board: cb2s
