substitutions:
    name: base-board-esp32-c6-devkitc-1
    friendly_name: Base Board ESP32-C6-DevKitC-1

packages:
    Base Board: github://ngorchilov/huya-configs/base-board.yaml

esp32:
    board: esp32-c6-devkitc-1
    variant: esp32c6
    framework:
        type: esp-idf
