substitutions:
    name: base-board-wbr3
    friendly_name: Base Board WBR3

packages:
    Base Board: github://ngorchilov/huya-configs/base-board.yaml

rtl87xx:
    board: generic-rtl8720cf-2mb-992k
    framework:
        version: 0.0.0
        source: https://github.com/prokoma/libretiny#55aacc8 # add support for ota on rtl8720cf

captive_portal: !remove # incompatible with this source

sensor:
    - id: !remove mcu_temperature

text_sensor:
    - platform: libretiny
      version:
          name: LibreTiny Version
          id: mcu_version_libretiny
