substitutions:
    name: base-board-esp32-s3-devkitc-1
    friendly_name: Base Board ESP32-S3-DevKitC-1

packages:
    Base Board: github://ngorchilov/huya-configs/base-board.yaml

esp32:
    board: esp32-s3-devkitc-1
    variant: esp32s3
    framework:
        type: esp-idf
