substitutions:
  name: base-board-cb3s
  friendly_name: Base Board CB3S

packages:
  Base Board Template (BEKEN): github://ngorchilov/huya-configs/base-board-template-libretiny-beken.yaml

bk72xx:
  board: cb3s
