substitutions:
    name: base-board
    friendly_name: Base Board

esphome:
    name: ${name}
    friendly_name: ${friendly_name}

logger:
    level: INFO

api:

ota:
    - platform: esphome

wifi:
    ssid: !secret wifi_ssid
    password: !secret wifi_password

    ap:
        ssid: Huya-WiFi

mdns:
    disabled: false

captive_portal:

button:
    - platform: restart
      name: MCU Restart
      id: mcu_restart

sensor:
    - platform: uptime
      name: Uptime
      id: mcu_uptime
      unit_of_measurement: s
      device_class: duration
      state_class: measurement
      suggested_display_precision: 0

    - platform: wifi_signal
      name: WiFi Signal
      id: mcu_wifi_signal

    - platform: internal_temperature
      name: MCU Temperature
      id: mcu_temperature

binary_sensor:
    - platform: status
      name: Status
      id: mcu_status

text_sensor:
    - platform: wifi_info
      ip_address:
          name: IP
          id: mcu_ip
      ssid:
          name: SSID
          id: mcu_ssid
      bssid:
          name: BSSID
          id: mcu_bssid
      mac_address:
          name: MAC Address
          id: mcu_mac_address

    - platform: version
      name: ESPhome Version
      id: mcu_version_esphome
      hide_timestamp: true

time:
    - platform: homeassistant
      id: ha_time
