substitutions:
    name: base-board-cb2s
    friendly_name: Base Board CB2S

packages:
    Base Board Template (LibreTiny): github://ngorchilov/huya-configs/base-board-template-libretiny.yaml

bk72xx:
    board: cb2s