substitutions:
  name: base-board-template-esphome-esp32
  friendly_name: Base Board Template ESPHome (ESP32)

packages:
  Base Board Template (ESPHome): github://ngorchilov/huya-configs/base-board-template-esphome.yaml

esp32:
  framework:
    type: esp-idf
