substitutions:
    name: base-board-esp32-c3-devkitm-1
    friendly_name: Base Board ESP32-C3-DevKitM-1

packages:
    Base Board Template (ESPHome): github://ngorchilov/huya-configs/base-board-template-esphome.yaml

esp32:
    board: esp32-c3-devkitm-1
    variant: esp32c3