substitutions:
    name: base-board-cbu
    friendly_name: Base Board CBU

packages:
    Base Board Template (LibreTiny): github://ngorchilov/huya-configs/base-board-template-libretiny.yaml

bk72xx:
    board: cbu