substitutions:
    name: base-board-cb2s
    friendly_name: Base Board CB2S

packages:
    Base Board: github://ngorchilov/huya-configs/base-board.yaml

bk72xx:
    board: cb2s

text_sensor:
    - platform: libretiny
      version:
          name: LibreTiny Version
