substitutions:
    name: base-board-bk7231n-generic
    friendly_name: Base Board BK7231N Generic

packages:
    Base Board Template (LibreTiny): github://ngorchilov/huya-configs/base-board-template-libretiny.yaml

bk72xx:
    board: generic-bk7231n-qfn32-tuya