substitutions:
    name: base-board-bk7231n-generic
    friendly_name: Base Board BK7231N Generic

packages:
    Base Board: github://ngorchilov/huya-configs/base-board.yaml

bk72xx:
    board: generic-bk7231n-qfn32-tuya

text_sensor:
    - platform: libretiny
      version:
          name: LibreTiny Version
          id: mcu_version_libretiny
