substitutions:
  name: base-board-esp32-s3-devkitc-1
  friendly_name: Base Board ESP32-S3-DevKitC-1

packages:
  Base Board Template (ESP32): github://ngorchilov/huya-configs/base-board-template-esphome-esp32.yaml

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
