substitutions:
    name: base-board-esp32-c3-devkitm-1
    friendly_name: Base Board ESP32-C3-DevKitC-1

packages:
    Base Board: github://ngorchilov/huya-configs/base-board.yaml

esp32:
    board: esp32-c3-devkitc-1
    variant: esp32c3
    framework:
        type: esp-idf
