substitutions:
    name: base-board-wbr3
    friendly_name: Base Board WBR3

packages:
    Base Board: github://ngorchilov/huya-configs/base-board.yaml

rtl87xx:
    board: wbr3

text_sensor:
    - platform: libretiny
      version:
          name: LibreTiny Version
          id: mcu_version_libretiny
