# HLW8012 Energy Monitoring Module
# Usage: Include this package in devices using the HLW8012 chip for energy monitoring.

substitutions:
    hlw8012_cf_pin: GPIO6 # Default CF pin for HLW8012 (can be overridden in the main config)
    hlw8012_cf1_pin: GPIO8 # Default CF1 pin for HLW8012 (can be overridden in the main config)
    hlw8012_sel_pin: GPIO11 # Default SEL pin for HLW8012 (can be overridden in the main config)
    hlw8012_voltage_divider: 775 # Default voltage divider (can be overridden in the main config)
    hlw8012_current_resistor: 0.00104 ohm # Default current resistor (can be overridden in the main config)
    hlw8012_update_interval: 10s # Default update interval (can be overridden in the main config)

sensor:
    - platform: hlw8012
      model: BL0937
      cf_pin:
          number: ${hlw8012_cf_pin}
          inverted: true
      cf1_pin:
          number: ${hlw8012_cf1_pin}
          inverted: true
      sel_pin:
          number: ${hlw8012_sel_pin}
          inverted: true
      current:
          name: Current
      voltage:
          name: Voltage
      power:
          name: Power
      energy:
          name: Energy
      voltage_divider: ${hlw8012_voltage_divider}
      current_resistor: ${hlw8012_current_resistor}
      update_interval: ${hlw8012_update_interval}
