substitutions:
    rgb_pin: GPIO1
    uart_tx_pin: GPIO16
    uart_rx_pin: GPIO17
    i2c_sda_pin: GPIO22
    i2c_scl_pin: GPIO23
    bh1750_address: 0x23
    bh1750_interval: 1s

uart:
    id: seeed_mr60fda2_uart
    baud_rate: 115200
    rx_pin: ${uart_rx_pin}
    tx_pin: ${uart_tx_pin}
    parity: NONE
    stop_bits: 1

i2c:
    sda: ${i2c_sda_pin}
    scl: ${i2c_scl_pin}
    scan: true
    id: bus_a

light:
    - platform: esp32_rmt_led_strip
      id: led_ring
      name: 'RGB Light'
      pin: ${rgb_pin}
      num_leds: 1
      #rmt_channel: 0
      rgb_order: GRB
      chipset: ws2812

sensor:
    - platform: bh1750
      name: 'Illuminance'
      address: ${bh1750_address}
      update_interval: ${bh1750_interval}

seeed_mr60fda2:
    id: my_seeed_mr60fda2
    uart_id: seeed_mr60fda2_uart

binary_sensor:
    - platform: seeed_mr60fda2
      people_exist:
          name: 'Person Information'
      fall_detected:
          name: 'Falling Detected'

button:
    - platform: seeed_mr60fda2
      get_radar_parameters:
          name: 'Get Radar Parameters'
      factory_reset:
          name: 'Reset'

select:
    - platform: seeed_mr60fda2
      install_height:
          name: 'Set Install Height'
      height_threshold:
          name: 'Set Height Threshold'
      sensitivity:
          name: 'Set Sensitivity'
